name: rulesets-required-workflow

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - sychronize
      - ready_for_review

jobs:
  rulesets-required-workflow-job:
    if: github.event.pull_request.draft == false && github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
